language: generic 
sudo : required
services:
  - docker

before_install:
  - docker build -t ramyakanguri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ramyakanguri/react-test npm test

after_success:
  - docker build -t ramyakanguri/multi-client ./client
  - docker build -t ramyakanguri/multi-nginx ./nginx
  - docker build -t ramyakanguri/multi-server ./server
  - docker build -t ramyakanguri/multi-worker ./worker
  
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker hub
  - docker push ramyakanguri/multi-client
  - docker push ramyakanguri/multi-nginx
  - docker push ramyakanguri/multi-server
  - docker push ramyakanguri/multi-worker 
